// Flag icons using CSS classes from flag-icons package
// The actual SVGs are loaded via CSS background images

export const flagClassNames: Record<string, string> = {
  dz: "fi fi-dz",
  ar: "fi fi-ar",
  au: "fi fi-au",
  at: "fi fi-at",
  be: "fi fi-be",
  ba: "fi fi-ba",
  br: "fi fi-br",
  ca: "fi fi-ca",
  cv: "fi fi-cv",
  co: "fi fi-co",
  hr: "fi fi-hr",
  cw: "fi fi-cw",
  cz: "fi fi-cz",
  cd: "fi fi-cd",
  ec: "fi fi-ec",
  eg: "fi fi-eg",
  "gb-eng": "fi fi-gb-eng",
  fr: "fi fi-fr",
  de: "fi fi-de",
  gh: "fi fi-gh",
  ht: "fi fi-ht",
  ir: "fi fi-ir",
  iq: "fi fi-iq",
  ci: "fi fi-ci",
  jp: "fi fi-jp",
  jo: "fi fi-jo",
  mx: "fi fi-mx",
  ma: "fi fi-ma",
  nl: "fi fi-nl",
  nz: "fi fi-nz",
  no: "fi fi-no",
  pa: "fi fi-pa",
  py: "fi fi-py",
  pt: "fi fi-pt",
  qa: "fi fi-qa",
  sa: "fi fi-sa",
  "gb-sct": "fi fi-gb-sct",
  sn: "fi fi-sn",
  za: "fi fi-za",
  kr: "fi fi-kr",
  es: "fi fi-es",
  se: "fi fi-se",
  ch: "fi fi-ch",
  tn: "fi fi-tn",
  tr: "fi fi-tr",
  us: "fi fi-us",
  uy: "fi fi-uy",
  uz: "fi fi-uz",
};
